# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# so lets modify

{ config, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./fs.nix
    ./boot.nix
  ];
  # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  
  # hardware.enableRedistributableFirmware = true;
  # hardware.firmware = with pkgs.linux; [ ( linuxFirmware.iwlwifi_so_a0_hr_b0_72.ucode ) ];

  # uncomment this if micro code error on old intel device
  # hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.nvidia = {
    prime = {
      offload.enable = true;
      offload.enableOffloadCmd = true;
      intelBusId = "PCI:0:2:0";
      nvidiaBusId = "PCI:1:0:0";
    };

    modesetting.enable = true;

    powerManagement = {
      enable = true;
      finegrained = true;
    };

    nvidiaSettings = false; # gui app
    open = false;
    package = config.boot.kernelPackages.nvidiaPackages.latest;
  };
  hardware.graphics.enable = true;
  hardware.bluetooth.enable = true; # enables support for Bluetooth
  hardware.bluetooth.powerOnBoot = false;
}
